@baseUrl = http://localhost:2222
@authToken = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas de Brasília",
  "email": "luquinhasdohack@gmail.com",
  "password": "soutroll"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "luquinhasdohack@gmail.com",
  "password": "soutroll"
}


###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 2",
  "content": "Resposta da pergunta 2"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###